services:
  - type: web
    name: dpl-admin-dashboard
    env: node
    plan: free
    buildCommand: |
      cd client && npm install && npm run build && cd .. && npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 8080
      - key: FRONTEND_URL
        sync: false
    autoDeploy: true
